cac = input('Digita qualquer coisa: ')
print('O tipo primitivo (classe) desse valor é {}' .format(type(cac)))
print('Está em maiúsculo? {}' .format(cac.isupper()))
print('Está em minúsculo? {}' .format(cac.islower()))
print('Está capitalizada? {}' .format(cac.istitle()))
print('Tem apenas letras? {}' .format(cac.isalpha()))
print('É somente espaços? {}' .format(cac.isspace()))
print('É um número? {}' .format(cac.isnumeric()))
print('É alfanumérico? {}' .format(cac.isalnum()))
